/**
 * Autogenerated by feeding the context.json file to https://app.quicktype.io/
 */

export interface IContext {
  SCENARIO:  string;
  STACK_ID:  string;
  PREFIXES:  Prefixes;
  ACCOUNT:   string;
  REGION:    string;
  VPC_ID:    string;
  CIDRS:     Cidrs;
  SUBNETS:   Subnets;
  DNS:       DNS;
  S3PROXY:   S3Proxy;
  WORDPRESS: Wordpress;
  TAGS:      Tags;
}

export interface Cidrs {
  campus1:       string;
  campus2:       string;
  campus3:       string;
  campus4:       string;
  campus5:       string;
  "wp-app-dv02": string;
}

export interface DNS {
  hostedZone:     string;
  certificateARN: string;
}

export interface Prefixes {
  wordpress: string;
  s3proxy:   string;
  rds:       string;
}

export interface S3Proxy {
  dockerImage:          string;
  bucketUserSecretName: string;
  recordName:           string;
  OLAP:                 string;
}

export interface Subnets {
  campus1: string;
  campus2: string;
}

export interface Tags {
  Service:   string;
  Function:  string;
  Landscape: string;
}

export interface Wordpress {
  dockerImage: string;
  env:         Env;
  secrets:     Secrets;
}

export interface Env {
  serverName:      string;
  spEntityId:      string;
  idpEntityId:     string;
  forwardedForHost: string;
  recordName:      string;
  TZ:              string;
}

export interface Secrets {
  configExtra: string;
}
